name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test --coverage

    - name: Code coverage
      run: bash <(curl -s https://codecov.io/bash)

    - name: Build docker container
      run: |
        docker build -t ${{ github.repository }} .
        echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
        docker push ${{ github.repository }}
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

    - name: Deploy app
      run: |
        echo "$SSH_IDENTITY_KEY" > identity
        chmod 600 identity
        ssh -i identity -o StrictHostKeyChecking=no root@twi2img.ailinykh.com "/bin/bash ./${{ github.repository }}/deploy_app.sh $TAG"
      env:
        SSH_IDENTITY_KEY: ${{ secrets.SSH_IDENTITY_KEY }}
